# Generated by Django 3.2.25 on 2024-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionld', '0002_daily_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
