# Generated by Django 5.0.6 on 2024-05-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionld', '0005_alter_daily_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('hint', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionld.response'),
            preserve_default=False,
        ),
    ]
