# Generated by Django 5.0.6 on 2024-05-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionld', '0006_response_daily_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='details',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
